services:
  web1:
    build: .
    deploy:
      resources:
        limits:
          cpus: "0.45"
          memory: "85MB"
    networks:
      - payment-processor
    expose:
      - "3000"

  web2:
    build: .
    deploy:
      resources:
        limits:
          cpus: "0.45"
          memory: "85MB"
    networks:
      - payment-processor
    expose:
      - "3000"

  nginx:
    image: nginx:1.25
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "9999:9999"
    depends_on:
      - web1
      - web2
    deploy:
      resources:
        limits:
          cpus: "0.1"
          memory: "30MB"
    networks:
      - payment-processor

networks:
  payment-processor:
    external: true
