services:
  web1:
    build: .
    environment:
      REDIS_HOST: cache
      REDIS_PORT: 6379
    depends_on:
      - cache
    deploy:
      resources:
        limits:
          cpus: "0.45"
          memory: "85MB"
    networks:
      - payment-processor
      - backend
    expose:
      - "3000"

  web2:
    build: .
    environment:
      REDIS_HOST: cache
      REDIS_PORT: 6379
    depends_on:
      - cache
    deploy:
      resources:
        limits:
          cpus: "0.45"
          memory: "85MB"
    networks:
      - payment-processor
      - backend
    expose:
      - "3000"

  cache:
    image: redis
    ports:
      - 6379:6379
    deploy:
      resources:
        limits:
          cpus: "0.5"
          memory: "30MB"
    networks:
      - backend
    expose:
      - "3000"

  nginx:
    image: nginx:1.25
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "9999:80"
    depends_on:
      - web1
      - web2
    deploy:
      resources:
        limits:
          cpus: "0.1"
          memory: "30MB"
    networks:
      - payment-processor

networks:
  payment-processor:
    external: true
  backend:
    driver: bridge
